### ISSUE TITLE
Readme needs a tweak about the demo

### ISSUE THREAD

**Issue by ruhowe** [bbc/storyplayer#724]
Hi folks,

Thanks for all this amazing work.

The readme still has instructions for seeing the demo online via a link to the index.html in examples, which you've removed now because you're building the demo another way:

> _The demo index page [here](https://github.com/bbc/storyplayer/blob/main/examples/index.html) shows how this might work in a static HTML context, with simple fetchers all reading from the same single pre-loaded JSON file for the story._

So to begin with when I was just wanting to see a demo online, it took me a few minutes of messing about looking in the github history to figure out that there's no longer an online demo and to keep reading down beyond _Building the library from the repo_ to see that I could clone & run `npm install` and `npm run dev` to see it at [http://localhost:5173](http://localhost:5173)

Would be good if you could edit this para to say that the demo can be run locally using the instructions below.

**Comment by andy-brown** [comment]
Hopefully clearer now #721 is in.
